CREATE TABLE IF NOT EXISTS post (
  id BIGSERIAL PRIMARY KEY,
  "user" VARCHAR(255),
  content TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

ALTER TABLE post
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE post
ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;